name: Publish Adapters

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build-adapters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Build adapters and docker images
        run: bunx turbo run build-adapter-docker

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish adapters
        run: |
          images=`docker image ls --format '{{.Repository}}:{{.Tag}}' | grep ghcr.io`
          for image in $images; do
            docker push $image
          done
